language: python
sudo: false
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.5
    env: TOXENV=py35
  - python: 3.4
    env: TOXENV=py34
install:
- pip install -U tox
script:
- tox
before_install:
- sleep 15
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: Lundberg
  password:
    secure: H5d+Its9YTMSvVddRWX2qgChMb8Eur5zI+qRy3NAPdwRNs1RNyIk1a2z9/EPFmRIu6OsBBDcHsCiq4VXcwvpigdAqMu4iAoZ/Xe0xf88k21GCggfaAPbINRVL6031RFUQkfGZ4abT2cXnerDylMv2DporPZkfCEUJonq+we0GmtJHoCSemXewMxt28TSu0aPKRL4aBfbuRoAPx50jUns9ekxgc0sqpSLvE5qyxWxXIePK0/+8tX3OrdCcKMg/IshgoK7Yondu+DhN+qhf+AkQuPDXUQTx/TKdg/YDVqj8SHT6hIFFi6dCakuhkYIKlkggnSguLhZ2zhVUjYFt1f0NOv2j7dHuKxyUFR9Qm/49rdY/E3ir3CU5YgUEprcgo/jj5K3B1/jY2uXNez1JD97RC6IAPg4o+PwenVQ9a3pLwqnImSaJKPTQf9IyFfrV/xru3ZyQiftmUmCYtCPybDATOq5iqNAQa9Ec0Mg54OGcabPQkNp9CrNFkcO0sM3VNRnGTmuqdYIkjNxPwNCzjbAQKlwcXVNg48kHjH6vb9D+mxjt9CYwCJdfkGm2F2pekr5S8tDdLAkxE9VW+r7SrsRaJRFCHU+6AaejnWvOLCy2S+KJ0JhQesJm0k1iT2fsC8v92MKIzghrY/sqKck33pxB57cFqxLIQIVYgCaBFWbwfc=
  on:
    tags: true
    repo: IdentityPython/pyop
